# Generated by Django 4.1.4 on 2022-12-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("WeatherApp", "0006_alter_city_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={},
        ),
        migrations.AlterModelTable(
            name="city",
            table="city",
        ),
    ]
